batch_size: 128
benchmark_dir: benchmark_results
data_root: data/SWAT/
dataset: swat
dataset_id: SWAT
device: -1
dim: 51
entities:
- swat
eval:
  best_params:
    target_direction: max
    target_metric: f1
  metrics:
  - f1
  - delay
  point_adjustment:
  - true
  - false
  pot_params:
    dynamic: false
    level:
    - 0.99
    - 0.98
    - 0.97
    - 0.9
    - 0.8
    q: 0.01
  thresholding:
  - best
  - pot
exp_id: anomaly_transformer_SWAT
k: 3
l2_regularizer: 0.1
lr: 0.0001
model_id: anomaly_transformer
model_root: benchmark_exp_details/SWAT/anomaly_transformer/anomaly_transformer_SWAT
nb_epoch: 1
normalize: minmax
nrows: null
num_workers: 1
stride: 1000
test_label_postfix: test_label.pkl
test_postfix: test.pkl
train_postfix: train.pkl
uptime: 20231120-163808
valid_ratio: 0
window_size: 10
